AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fake-photo-image-verifier stack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  BucketNamePrefix:
    Type: String
    Default: fake-photo-bucket

Resources:
  FakePhotoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 3
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "${BucketNamePrefix}"
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
  Bucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${BucketNamePrefix}"

Outputs:

  FakePhotoFunction:
    Description: "FakePhoto Lambda Function ARN"
    Value: !GetAtt FakePhotoFunction.Arn
  FakePhotoFunctionIamRole:
    Description: "Implicit IAM Role created for FakePhoto function"
    Value: !GetAtt FakePhotoFunctionRole.Arn

